project_name: CodeImprover
directory: "."
files:
  - utils.py
  - chatgpt.py
  - config.yaml
  - code_improver.py
  - Story_bullet_points.md

#
model: gpt-4 # gpt-3.5-turbo
#
role: "You play the role of a professional developer obsessed with clean code."
#
critic_prompt: "You are a researcher tasked with investigating the previous response provided. Split the response to logic parts and list the flaws and faulty logic for each part. Let's work this out in a step-by-step way to be sure we have all the errors:"
#
resolver_prompt: "You are a resolver tasked with 1) Improving the initial answer by fixing all the errors the researcher found, and 2) Printing the improved answer in full. Let's work this out in a step-by-step way to be sure we have the right answer:"
#
step_by_step_prompt: "Let's work this out in a step-by-step way to be sure we have the right answer:"